### ISSUE TITLE
rc_visard_driver not launching

### ISSUE THREAD

**Issue by dkanou** [roboception/rc_visard_ros#3] opened 2017-12-06 13:55 UTC
Having compiled the rc_visard_ros package and also beig able to use the webGUI, when I:
> roslaunch rc_visard_driver rc_visard_driver.launch

I get the following error:
**[ERROR] [1512568083.512790905]: rc_visard_driver: No transport layers found in path GENICAM_GENTL64_PATH
[ERROR] [1512568083.512878157]: rc_visard_driver: Failed or lost connection. Trying to recover rc_visard_driver from failed state (1/5)...**

Not sure if this a connectivity issue.

**Comment by heikohimu** [comment] 2017-12-06 14:30
The transport layer is a shared library with the suffix '.cti'. We provide them in sub folders of 'rc_visard_driver/ext/rc_genicam_api/baumer/Ubuntu-14.04' for different architectures. The (absolute path to the) transport layer for your architecture needs to be specified in the environment variable 'GENICAM_GENTL64_PATH'. That is the way it is defined in the GenICam standard. For convenience we have implemented a 'compiled in' fall back to the place where cmake installs the transport layer. However, this only works if you build and install the package as specified in 'rc_visard_driver/README.md'.

I think we need to describe this better in the readme.

**Comment by flixr** [comment] 2017-12-06 18:22
Closing as duplicate of #1

**Closed as completed by flixr** 2017-12-06 18:22 UTC
